/**
 * DOM contract attributes and identifiers for the selectable DOCX preview.
 *
 * These constants freeze the DOM structure the DOCX renderer publishes and the
 * DOCX selection adapter consumes.
 */

/** DSH DocumentPreviewDefinition id for the plugin's DOCX renderer. */
export const DOCX_RENDERER_ID = 'dsh-document-selection-ask/docx'

/** Stable adapter id for the plugin's selectable DOCX preview. */
export const DOCX_SELECTION_ADAPTER_ID = 'dsh-selectable-docx'

/** Document kind tag identifying DOCX previews in DOM markers. */
export const DOCX_DOCUMENT_KIND = 'docx'

/** Attribute marking the document root element with its format kind. */
export const DOCX_DOCUMENT_KIND_ATTRIBUTE = 'data-dsa-document-kind'

/** Attribute marking the document root element with its DSH resource address. */
export const DOCX_RESOURCE_ADDRESS_ATTRIBUTE = 'data-dsa-resource-address'

/** Attribute marking an individual rendered page container with its 1-based page number. */
export const DOCX_PAGE_ATTRIBUTE = 'data-dsa-docx-page'

/** Attribute marking the selectable content host element. */
export const DOCX_SELECTABLE_ATTRIBUTE = 'data-dsa-docx-content'

/** Attribute marking the scoped style host element for document CSS. */
export const DOCX_STYLE_HOST_ATTRIBUTE = 'data-dsa-docx-style-host'

/** Attribute marking an anchor whose hyperlink target was stripped by scheme policy. */
export const DOCX_BLOCKED_LINK_ATTRIBUTE = 'data-dsa-docx-blocked-link'

/** Default class name passed to docx-preview renderAsync. */
export const DOCX_ENGINE_CLASS_NAME = 'dsa-docx-engine'

/** Wrapper class name generated by docx-preview when inWrapper is true. */
export const DOCX_WRAPPER_CLASS_NAME = `${DOCX_ENGINE_CLASS_NAME}-wrapper`
